# Generated by Django 4.0 on 2022-02-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0003_rename_caption_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
